// Write synthetic sample recordings to samples/ (git-ignored) for trying the
// workbench. They are synthetic, not data cases; only real human
// measurements are tracked in this repository.
//   triphasic.csv            time (s), velocity (m/s), comma separated
//   monophasic_eu.csv        semicolon separated, decimal commas, ms and cm/s
//   irregular_rhythm.csv     AF-like RR variation
//   spectral_capture.dcm     DICOM with ultrasound-region calibration
//   spectral_screenshot.png  plain image; calibrate it by hand in the tool
// All data are synthetic. The true ACCmax/AT of each preset is listed in
// samples/README.md.

import { writeFileSync, mkdirSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { synthesize, syntheticTruth, renderSpectrogram } from '../web/js/core/synthetic.js';
import { spectralDicom } from './lib/dicom-writer.mjs';

const out = new URL('../samples/', import.meta.url);
mkdirSync(out, { recursive: true });

const csv = (sim, { sep = ',', dec = '.', tScale = 1, vScale = 1, header = 'time_s,velocity_m_s' } = {}) =>
  [header, ...Array.from(sim.t, (t, i) => `${(t * tScale).toFixed(tScale > 1 ? 1 : 4)}${sep}${(sim.v[i] * vScale).toFixed(vScale > 1 ? 2 : 4)}`.replaceAll('.', dec === '.' ? '.' : dec))].join('\n') + '\n';

const tri = synthesize({ preset: 'triphasic', hr: 66, duration: 8, noise: 0.02, seed: 101 });
writeFileSync(new URL('triphasic.csv', out), csv(tri));

const mono = synthesize({ preset: 'monophasic', hr: 74, duration: 8, noise: 0.006, seed: 202 });
writeFileSync(new URL('monophasic_eu.csv', out), csv(mono, { sep: ';', dec: ',', tScale: 1000, vScale: 100, header: 'tijd_ms;snelheid_cm_s' }));

const irr = synthesize({ preset: 'triphasic', hr: 88, duration: 10, noise: 0.02, rrSd: 0.15, seed: 303 });
writeFileSync(new URL('irregular_rhythm.csv', out), csv(irr));

const bi = synthesize({ preset: 'biphasic', hr: 62, duration: 5, noise: 0, seed: 404 });
const cal = { region: { x0: 46, y0: 24, x1: 866, y1: 318 }, baselineY: 262, velPerPx: 0.0025, secPerPx: 0.0045 };
const img = renderSpectrogram(bi, { width: 920, height: 352, ...cal, seed: 405 });
writeFileSync(new URL('spectral_capture.dcm', out), spectralDicom(img, cal, { dopplerAngle: 52 }));

// Minimal PNG encoder (RGBA, no filtering).
function png({ width, height, data }) {
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc = (buf) => {
    let c = 0xffffffff;
    for (const b of buf) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, body) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(body.length);
    const tb = Buffer.concat([Buffer.from(type, 'ascii'), body]);
    const c = Buffer.alloc(4);
    c.writeUInt32BE(crc(tb));
    return Buffer.concat([len, tb, c]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  const raw = Buffer.alloc((width * 4 + 1) * height);
  for (let y = 0; y < height; y++) Buffer.from(data.buffer, data.byteOffset + y * width * 4, width * 4).copy(raw, y * (width * 4 + 1) + 1);
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}
const mono2 = synthesize({ preset: 'monophasic', hr: 70, duration: 5, noise: 0, seed: 505 });
const cal2 = { region: { x0: 46, y0: 24, x1: 866, y1: 318 }, baselineY: 270, velPerPx: 0.0006, secPerPx: 0.0045 };
writeFileSync(new URL('spectral_screenshot.png', out), png(renderSpectrogram(mono2, { width: 920, height: 352, ...cal2, seed: 506 })));

const truth = (preset, hr) => {
  const t = syntheticTruth({ preset, hr });
  return `ACCmax ${t.accmax.toFixed(2)} m/s², AT ${(t.at * 1000).toFixed(0)} ms`;
};
const lines = [
  '# Sample recordings',
  '',
  'All files are synthetic, generated by `npm run samples` (scripts/make-samples.mjs).',
  'True values use the default definitions (20 ms tangent span, tangent-intersection onset).',
  '',
  '| File | Content | True values |',
  '| --- | --- | --- |',
  `| triphasic.csv | triphasic, 66 bpm, 8 s, comma separated, s and m/s | ${truth('triphasic', 66)} |`,
  `| monophasic_eu.csv | monophasic, 74 bpm, semicolons and decimal commas, ms and cm/s | ${truth('monophasic', 74)} |`,
  `| irregular_rhythm.csv | triphasic with AF-like RR variation (15%), 88 bpm | ${truth('triphasic', 88)} |`,
  `| spectral_capture.dcm | DICOM spectral display with ultrasound-region calibration (biphasic, 62 bpm) | ${truth('biphasic', 62)} |`,
  `| spectral_screenshot.png | plain screenshot (monophasic, 70 bpm). Calibrate by hand: baseline at y = ${cal2.baselineY} px, 10 cm/s = ${(0.1 / cal2.velPerPx).toFixed(1)} px, time marks every 0.2 s (${(0.2 / cal2.secPerPx).toFixed(1)} px) | ${truth('monophasic', 70)} |`,
  '',
];
writeFileSync(new URL('README.md', out), lines.join('\n'));
console.log('samples written');
