"""Render reference glyphs for reading the velocity scale of a spectral display.

Writes web/js/io/glyphs.js: each character of the scale labels (digits,
minus, decimal point, "cm/s", "bpm") in a few common sans-serif fonts,
cropped to its ink and scaled to a 20-pixel-high greyscale bitmap (16 levels).
The fonts are Liberation Sans (SIL Open Font License) and DejaVu Sans
(Bitstream Vera licence), both free to use.

Run: python3 scripts/make-glyphs.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = [
    ("Liberation Sans Bold", "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"),
    ("Liberation Sans", "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"),
    ("DejaVu Sans Bold", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
    ("DejaVu Sans", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
]
CHARS = "0123456789cms/bp"
HEIGHT = 20


def render(font_path, ch):
    font = ImageFont.truetype(font_path, 96)
    img = Image.new("L", (160, 160), 0)
    ImageDraw.Draw(img).text((30, 10), ch, fill=255, font=font)
    box = img.getbbox()
    glyph = img.crop(box)
    w, h = glyph.size
    return glyph.resize((max(1, round(w * HEIGHT / h)), HEIGHT), Image.BOX)


def main():
    entries = []
    for name, path in FONTS:
        for ch in CHARS:
            g = render(path, ch)
            w, h = g.size
            px = "".join("0123456789abcdef"[min(15, round(v / 17))] for v in g.tobytes())
            entries.append(f"  [{ch!r}, {w}, {h}, '{px}'],  // {name}")
    js = (
        "// Generated by scripts/make-glyphs.py: reference glyphs for reading the\n"
        "// labels of a spectral display's velocity scale. Each entry is\n"
        "// [character, width, height, pixels as 16-level hex, row by row].\n"
        "// Fonts: Liberation Sans (SIL OFL 1.1) and DejaVu Sans (Bitstream Vera licence).\n"
        "export const GLYPHS = [\n" + "\n".join(entries) + "\n];\n"
    )
    out = ROOT / "web/js/io/glyphs.js"
    out.write_text(js)
    print(f"wrote {out.relative_to(ROOT)}: {len(entries)} glyphs, {len(js)} bytes")


if __name__ == "__main__":
    main()
